apiVersion: v1
kind: Service
metadata:
  labels:
    app: schoolay
    heritage: Tiller
    release: schoolay
  name: schoolay
spec:
  ports:
  - name: api
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: schoolay
    release: schoolay
    role: railsAppServer
  sessionAffinity: None
  type: LoadBalancer